In [1]:
from numpy import *

In [2]:
random.rand(4, 4)

array([[0.96625776, 0.61115858, 0.76074318, 0.44472965],
       [0.07564271, 0.62818875, 0.0843795 , 0.13726672],
       [0.04562207, 0.45948991, 0.16264347, 0.87225572],
       [0.28914955, 0.57641087, 0.32237395, 0.82850041]])

In [3]:
randMat = mat(random.rand(4, 4))
randMat

matrix([[0.56239825, 0.11578481, 0.33449556, 0.69949251],
        [0.31691578, 0.27066954, 0.87508795, 0.42988591],
        [0.44667502, 0.99367463, 0.45102046, 0.15817762],
        [0.17681022, 0.95667019, 0.32972732, 0.23339223]])

In [4]:
randMat.I

matrix([[ 0.74843028, -0.69387465,  2.96658776, -2.97560135],
        [-0.15512865, -0.38311955,  0.00516028,  1.16710304],
        [-0.83959868,  1.5780188 ,  0.12570249, -0.47541591],
        [ 1.25503516, -0.1333066 , -2.44612795,  2.42656594]])

In [5]:
invRandMat = randMat.I

In [6]:
randMat * invRandMat

matrix([[ 1.00000000e+00,  0.00000000e+00, -2.22044605e-16,
          0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [-4.85722573e-17,  0.00000000e+00,  1.00000000e+00,
          4.44089210e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]])

In [7]:
myEye = randMat * invRandMat
myEye - eye(4)

matrix([[ 0.00000000e+00,  0.00000000e+00, -2.22044605e-16,
          0.00000000e+00],
        [ 0.00000000e+00, -1.11022302e-16,  0.00000000e+00,
          0.00000000e+00],
        [-4.85722573e-17,  0.00000000e+00, -2.22044605e-16,
          4.44089210e-16],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00]])