In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import mglearn

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier

iris=load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, random_state=42)

gbrt=GradientBoostingClassifier(learning_rate=0.1, random_state=0)
gbrt.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=0, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [2]:
print('Decision function shape: {}'.format(gbrt.decision_function(X_test).shape))
print('Decision function:\n{}'.format(gbrt.decision_function(X_test)[:6,:]))

Decision function shape: (38, 3)
Decision function:
[[-6.52410155  1.76139927 -5.83242466]
 [ 4.58962941 -3.57027324 -6.43717634]
 [-6.50290054 -6.35572472  4.2560087 ]
 [-6.52410155  2.32787828 -5.24096147]
 [-6.54957621  2.19012917 -5.42835855]
 [ 4.58962941 -3.9448458  -6.43717634]]


In [3]:
print('Argmax of decision function:\n{}'.format(np.argmax(gbrt.decision_function(X_test), axis=1)))
print('Predictions:\n{}'.format(gbrt.predict(X_test)))

Argmax of decision function:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]
Predictions:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [4]:
print('Predicted probabilities:\n{}'.format(gbrt.predict_proba(X_test)[:6]))
print('Sums: {}'.format(gbrt.predict_proba(X_test)[:6].sum(axis=1)))

Predicted probabilities:
[[2.51955965e-04 9.99244872e-01 5.03171575e-04]
 [9.99697941e-01 2.85803870e-04 1.62550350e-05]
 [2.12542195e-05 2.46242384e-05 9.99954122e-01]
 [1.43003851e-04 9.99341045e-01 5.15950912e-04]
 [1.59996830e-04 9.99349039e-01 4.90964420e-04]
 [9.99787212e-01 1.96531465e-04 1.62564865e-05]]
Sums: [1. 1. 1. 1. 1. 1.]


In [5]:
print('Argmax of predicted probabilities:\n{}'.format(np.argmax(gbrt.predict_proba(X_test), axis=1)))
print('Predictions:\n{}'.format(gbrt.predict(X_test)))

Argmax of predicted probabilities:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]
Predictions:
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [6]:
from sklearn.linear_model import LogisticRegression

logreg=LogisticRegression()

named_target=iris.target_names[y_train]
logreg.fit(X_train, named_target)
print('Unique classes in training data: {}'.format(logreg.classes_))
print('Predictions: {}'.format(logreg.predict(X_test)[:10]))
argmax_dec_func=np.argmax(logreg.decision_function(X_test),axis=1)
print('Argmax of decision function: {}'.format(argmax_dec_func[:10]))
print('Argmax combined with classes_: {}'.format(logreg.classes_[argmax_dec_func][:10]))

Unique classes in training data: ['setosa' 'versicolor' 'virginica']
Predictions: ['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor']
Argmax of decision function: [1 0 2 1 1 0 1 2 1 1]
Argmax combined with classes_: ['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor']
